# Generated by Django 5.2.1 on 2025-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], default='painting', max_length=50),
        ),
    ]
