# Generated by Django 5.2.1 on 2025-06-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
