# Generated by Django 5.2.1 on 2025-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_artist_is_sold'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'artwork'),
            name='unique_cart_artwork'),
        ),
    ]
