# Generated by Django 5.2.1 on 2025-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_cartitem_unique_cart_artwork'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_artwork',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'artwork'), name='unique_cart_artwork'),
        ),
    ]
