# Generated by Django 5.2.1 on 2025-06-13 08:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_remove_cartitem_unique_cart_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
