# Generated by Django 5.2.3 on 2025-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_artwork_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
