# Generated by Django 5.2.1 on 2025-06-18 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_remove_artist_is_sold_artist_image_artwork_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
